config/routes.rb
Rails.application.routes.draw do
  resources :videolists
 get "video/video_page"
 get "video/video_view"

  root 'video#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/videolist.rb
class Videolist < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author)
    end
end

app/controllers/video_controller.rb
class VideoController < ApplicationController
def index
#render "video_page"
end
def video_page
render "video_page"
end
def video_view
end

end

app/controllers/videolists_controller.rb
class VideolistsController < ApplicationController
  before_action :set_videolist, only: [:show, :edit, :update, :destroy]

  # GET /videolists
  # GET /videolists.json
  def index
    @videolists = Videolist.all
  end

  # GET /videolists/1
  # GET /videolists/1.json
  def show
  end

  # GET /videolists/new
  def new
    @videolist = Videolist.new
  end

  # GET /videolists/1/edit
  def edit
  end

  # POST /videolists
  # POST /videolists.json
  def create
    @videolist = Videolist.new(videolist_params)

    respond_to do |format|
      if @videolist.save
        format.html { redirect_to @videolist, notice: 'Videolist was successfully created.' }
        format.json { render :show, status: :created, location: @videolist }
      else
        format.html { render :new }
        format.json { render json: @videolist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videolists/1
  # PATCH/PUT /videolists/1.json
  def update
    respond_to do |format|
      if @videolist.update(videolist_params)
        format.html { redirect_to @videolist, notice: 'Videolist was successfully updated.' }
        format.json { render :show, status: :ok, location: @videolist }
      else
        format.html { render :edit }
        format.json { render json: @videolist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videolists/1
  # DELETE /videolists/1.json
  def destroy
    @videolist.destroy
    respond_to do |format|
      format.html { redirect_to videolists_url, notice: 'Videolist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_videolist
      @videolist = Videolist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def videolist_params
      params.require(:videolist).permit(:videoid, :videoURL, :flag, :title, :category, :author, :description, :uptime, :tag)
    end
end

app/controllers/welcome_controller.rb
# coding: utf-8
class WelcomeController < ApplicationController
 
require 'youtube_search'
require 'pp'
 
keyword = "GLAY 函館"
option = {
  :per_page => "10",
  :page     => "5",
}
 
videos = YoutubeSearch::search(keyword, option)
 
p "video count is #{videos.count}"
p "--------------------------------"
 
videos.each do |video|
  p video["video_id"]
  p video["title"]
  p video["content"]
  p "---------------------------------"

end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/video_helper.rb
module VideoHelper
end

app/helpers/videolists_helper.rb
module VideolistsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Listing books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EnpitB</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/video/index.html.erb
<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <title>Bluebee - UI</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/bootstrap/3.3.0/css/bootstrap.min.css">

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/bootstrap/3.3.0/css/bootstrap-theme.min.css">

        <!-- Latest compiled and minified JavaScript -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/bootstrap/3.3.0/js/bootstrap.min.js"></script>
        <script src="pakery.js" type="text/javascript"></script>
        <style>.top-buffer { margin-top:40px; }</style>
    </head>
    <body>
        <div class="container">
            <div class="row clearfix top-buffer">
                <div class="col-md-12 column">
                    <ul class="nav nav-tabs">
                        <li class="active">
                            <a href="#">Home</a>
                        </li>
                        <li>
                            <a href="../video/video_page">VideoList</a>
                        </li>
                        <li class="active">
                            <a href="#">Messages</a>
                        </li>
                        <li class="dropdown pull-right">
                            <a href="#" data-toggle="dropdown" class="dropdown-toggle">Dropdown<strong class="caret"></strong></a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="#">Action</a>
                                </li>
                                <li>
                                    <a href="#">Another action</a>
                                </li>
                                <li>
                                    <a href="#">Something else here</a>
                                </li>
                                <li class="divider">
                                </li>
                                <li>
                                    <a href="#">Separated link</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="row clearfix top-buffer">
                <div class="col-md-12 column">
                    <div class="carousel slide" id="carousel-143186">
                        <ol class="carousel-indicators">
                            <li class="active" data-slide-to="0" data-target="#carousel-143186">
                            </li>
                            <li data-slide-to="1" data-target="#carousel-143186">
                            </li>
                            <li data-slide-to="2" data-target="#carousel-143186">
                            </li>
                        </ol>
                        <div class="carousel-inner">
                            <div class="item active">
                                <img alt="" src="http://lorempixel.com/1600/500/sports/1" />
                                <div class="carousel-caption">
                                    <h4>
                                        First Thumbnail label
                                    </h4>
                                    <p>
                                        Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
                                    </p>
                                </div>
                            </div>
                            <div class="item">
                                <img alt="" src="http://lorempixel.com/1600/500/sports/2" />
                                <div class="carousel-caption">
                                    <h4>
                                        Second Thumbnail label
                                    </h4>
                                    <p>
                                        Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
                                    </p>
                                </div>
                            </div>
                            <div class="item">
                                <img alt="" src="http://lorempixel.com/1600/500/sports/3" />
                                <div class="carousel-caption">
                                    <h4>
                                        Third Thumbnail label
                                    </h4>
                                    <p>
                                        Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
                                    </p>
                                </div>
                            </div>
                        </div> <a class="left carousel-control" href="#carousel-143186" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a> <a class="right carousel-control" href="#carousel-143186" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
                    </div>
                    <div class="row top-buffer">
                        <div class="col-md-4">
                            <div class="thumbnail">
                                <img alt="300x200" src="http://lorempixel.com/600/200/people" />
                                <div class="caption">
                                    <h3>
                                        Thumbnail label
                                    </h3>
                                    <p>
                                        Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
                                    </p>
                                    <p>
                                        <a class="btn btn-primary" href="#">Action</a> <a class="btn" href="#">Action</a>
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="thumbnail">
                                <img alt="300x200" src="http://lorempixel.com/600/200/city" />
                                <div class="caption">
                                    <h3>
                                        Thumbnail label
                                    </h3>
                                    <p>
                                        Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
                                    </p>
                                    <p>
                                        <a class="btn btn-primary" href="#">Action</a> <a class="btn" href="#">Action</a>
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="thumbnail">
                                <img alt="300x200" src="http://lorempixel.com/600/200/sports" />
                                <div class="caption">
                                    <h3>
                                        Thumbnail label
                                    </h3>
                                    <p>
                                        Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
                                    </p>
                                    <p>
                                        <a class="btn btn-primary" href="#">Action</a> <a class="btn" href="#">Action</a>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row clearfix top-buffer">
                        <div class="col-md-7 column">
                         <div class="jumbotron">
				<h1>
					Hello, world!
				</h1>
				<p>
					This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.
				</p>
				<p>
					<a class="btn btn-primary btn-large" href="#">Learn more</a>
				</p>
			</div>
                        </div>
                        <div class="col-md-5 column">
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix top-buffer">
                <div class="col-md-5 column">
                </div>
                <div class="col-md-7 column">
                   <div class="jumbotron">
				<h1>
					Hello, world!
				</h1>
				<p>
					This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.
				</p>
				<p>
					<a class="btn btn-primary btn-large" href="#">Learn more</a>
				</p>
			</div>
                </div>
            </div>
            <div class="row clearfix top-buffer">
		<div class="col-md-6 column">
			<blockquote>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.
				</p> <small>Someone famous <cite>Source Title</cite></small>
			</blockquote>
		</div>
		<div class="col-md-6 column">
			<blockquote>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.
				</p> <small>Someone famous <cite>Source Title</cite></small>
			</blockquote>
		</div>
	</div>
            <div class="row clearfix top-buffer">
		<div class="col-md-12 column">
			<p>
				Lorem ipsum dolor sit amet, <strong>consectetur adipiscing elit</strong>. Aliquam eget sapien sapien. Curabitur in metus urna. In hac habitasse platea dictumst. Phasellus eu sem sapien, sed vestibulum velit. Nam purus nibh, lacinia non faucibus et, pharetra in dolor. Sed iaculis posuere diam ut cursus. <em>Morbi commodo sodales nisi id sodales. Proin consectetur, nisi id commodo imperdiet, metus nunc consequat lectus, id bibendum diam velit et dui.</em> Proin massa magna, vulputate nec bibendum nec, posuere nec lacus. <small>Aliquam mi erat, aliquam vel luctus eu, pharetra quis elit. Nulla euismod ultrices massa, et feugiat ipsum consequat eu.</small>
			</p>
		</div>
	</div>
            <div class="row clearfix top-buffer">
		<div class="col-md-6 column">
			<p>
				Lorem ipsum dolor sit amet, <strong>consectetur adipiscing elit</strong>. Aliquam eget sapien sapien. Curabitur in metus urna. In hac habitasse platea dictumst. Phasellus eu sem sapien, sed vestibulum velit. Nam purus nibh, lacinia non faucibus et, pharetra in dolor. Sed iaculis posuere diam ut cursus. <em>Morbi commodo sodales nisi id sodales. Proin consectetur, nisi id commodo imperdiet, metus nunc consequat lectus, id bibendum diam velit et dui.</em> Proin massa magna, vulputate nec bibendum nec, posuere nec lacus. <small>Aliquam mi erat, aliquam vel luctus eu, pharetra quis elit. Nulla euismod ultrices massa, et feugiat ipsum consequat eu.</small>
			</p>
		</div>
		<div class="col-md-6 column">
			 <address> <strong>Twitter, Inc.</strong><br /> 795 Folsom Ave, Suite 600<br /> San Francisco, CA 94107<br /> <abbr title="Phone">P:</abbr> (123) 456-7890</address>
		</div>
	</div>
            
        </div>
    </body>
</html>

app/views/video/video_view.html.erb
<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <title>Bluebee - UI</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/bootstrap/3.3.0/css/bootstrap.min.css">
        <!-- Optional theme -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/bootstrap/3.3.0/css/bootstrap-theme.min.css">
        <!-- Latest compiled and minified JavaScript -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/bootstrap/3.3.0/js/bootstrap.min.js"></script>
        <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/jquery-ui.min.js"></script>
        <script src="jquery.touch-punch.min.js" type="text/javascript"></script>
        <script src="jquery.shapeshift.js" type="text/javascript"></script>

        <!-- Core Files -->
        <style>.top-buffer { margin-top:40px; }</style>

    </head>

    <body>
        <div class="container">
            <div class="row clearfix">
                <div class="col-md-12 column">
                    <div class="col-md-8 column">
                        <!--<iframe width="700" height="400" src="//www.youtube.com/embed/FjwecMDIkyc" frameborder="0" allowfullscreen></iframe> -->
                        <iframe width="600" height="400" src="//www.youtube.com/embed/BCGB1P_bC-A" frameborder="0" allowfullscreen></iframe>

</div>
                    <div class="col-md-4 column">
                        <h2>
                            cài đặt ruby trên win, chạy test rspec trong ROR 1 
                        </h2>
                        <p>Video được cung cấp bởi thầy Trương Anh Hoàng - Giảng viên đại học công nghệ - ĐHQGHN</p>
                        <p>
                            <a class="btn" href="#">View details »</a>
                        </p>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-md-12 column">
                    <h3>
                        Related Video:
                    </h3>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="thumbnail">
                                <img alt="300x200" src="http://lorempixel.com/600/200/people" />
                                <div class="caption">
                                    <h3>
                                        Thumbnail label
                                    </h3>
                                    <p>
                                        Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
                                    </p>
                                    <p>
                                        <a class="btn btn-primary" href="#">Action</a> <a class="btn" href="#">Action</a>
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="thumbnail">
                                <img alt="300x200" src="http://lorempixel.com/600/200/city" />
                                <div class="caption">
                                    <h3>
                                        Thumbnail label
                                    </h3>
                                    <p>
                                        Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
                                    </p>
                                    <p>
                                        <a class="btn btn-primary" href="#">Action</a> <a class="btn" href="#">Action</a>
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="thumbnail">
                                <img alt="300x200" src="http://lorempixel.com/600/200/sports" />
                                <div class="caption">
                                    <h3>
                                        Thumbnail label
                                    </h3>
                                    <p>
                                        Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
                                    </p>
                                    <p>
                                        <a class="btn btn-primary" href="#">Action</a> <a class="btn" href="#">Action</a>
                                    </p>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <div>
                <h3>Comment</h3>
                <div id="disqus_thread"></div>
                <script type="text/javascript">
                    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
                    var disqus_shortname = 'enpitb'; // required: replace example with your forum shortname

                    /* * * DON'T EDIT BELOW THIS LINE * * */
                    (function() {
                        var dsq = document.createElement('script');
                        dsq.type = 'text/javascript';
                        dsq.async = true;
                        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
                    })();
                </script>
                <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>


            </div>
        </div>
    </body>
</html>

app/views/videolists/_form.html.erb
<%= form_for(@videolist) do |f| %>
  <% if @videolist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@videolist.errors.count, "error") %> prohibited this videolist from being saved:</h2>

      <ul>
      <% @videolist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :videoid %><br>
    <%= f.text_field :videoid %>
  </div>
  <div class="field">
    <%= f.label :videoURL %><br>
    <%= f.text_field :videoURL %>
  </div>
  <div class="field">
    <%= f.label :flag %><br>
    <%= f.check_box :flag %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :uptime %><br>
    <%= f.datetime_select :uptime %>
  </div>
  <div class="field">
    <%= f.label :tag %><br>
    <%= f.text_area :tag %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/videolists/edit.html.erb
<h1>Editing videolist</h1>

<%= render 'form' %>

<%= link_to 'Show', @videolist %> |
<%= link_to 'Back', videolists_path %>

app/views/videolists/index.html.erb
<h1>Listing videolists</h1>

<table>
  <thead>
    <tr>
      <th>Videoid</th>
      <th>Videourl</th>
      <th>Flag</th>
      <th>Title</th>
      <th>Category</th>
      <th>Author</th>
      <th>Description</th>
      <th>Uptime</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videolists.each do |videolist| %>
      <tr>
        <td><%= videolist.videoid %></td>
        <td><%= videolist.videoURL %></td>
        <td><%= videolist.flag %></td>
        <td><%= videolist.title %></td>
        <td><%= videolist.category %></td>
        <td><%= videolist.author %></td>
        <td><%= videolist.description %></td>
        <td><%= videolist.uptime %></td>
        <td><%= videolist.tag %></td>
        <td><%= link_to 'Show', videolist %></td>
        <td><%= link_to 'Edit', edit_videolist_path(videolist) %></td>
        <td><%= link_to 'Destroy', videolist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Videolist', new_videolist_path %>

app/views/videolists/new.html.erb
<h1>New videolist</h1>

<%= render 'form' %>

<%= link_to 'Back', videolists_path %>

app/views/videolists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Videoid:</strong>
  <%= @videolist.videoid %>
</p>

<p>
  <strong>Videourl:</strong>
  <%= @videolist.videoURL %>
</p>

<p>
  <strong>Flag:</strong>
  <%= @videolist.flag %>
</p>

<p>
  <strong>Title:</strong>
  <%= @videolist.title %>
</p>

<p>
  <strong>Category:</strong>
  <%= @videolist.category %>
</p>

<p>
  <strong>Author:</strong>
  <%= @videolist.author %>
</p>

<p>
  <strong>Description:</strong>
  <%= @videolist.description %>
</p>

<p>
  <strong>Uptime:</strong>
  <%= @videolist.uptime %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @videolist.tag %>
</p>

<%= link_to 'Edit', edit_videolist_path(@videolist) %> |
<%= link_to 'Back', videolists_path %>

app/views/welcome/2014index.html.erb
<h2>Hello World</h2>
<p>
The time is now:<%= Time.now %>
</p>

<a href="../books">test link</a>
<p>sample video<p>
<iframe width="560" height="315" src="http://www.youtube.com/embed/Glny4jSciVI" frameborder="0" allowfullscreen></iframe>

<a href="../public_html/index.html">UIindex.html</a>
<a href="../public_html/video_page.html">UIindex.html</a>

app/views/welcome/index.html.erb
<h2>Hello World</h2>
<p>
The time is now:<%= Time.now %>
</p>

<a href="../books">test link</a>
<p>sample video<p>
<iframe width="560" height="315" src="http://www.youtube.com/embed/Glny4jSciVI" frameborder="0" allowfullscreen></iframe>